
stages:
  - template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      ArtifactName: ''
      ArtifactSafeName: ''
      CloudConfig:
        Public:
          SubscriptionConfigurations:
            - $(sub-config-azure-cloud-test-resources)
            - $(sub-config-communication-services-cloud-test-resources-common)
            - $(sub-config-communication-services-cloud-test-resources-java)
        Int:
          SubscriptionConfigurations:
            - $(sub-config-communication-int-test-resources-common)
            - $(sub-config-communication-int-test-resources-java)
      Clouds: Public, Int
      Artifacts:
        - name: ${{ parameters.ArtifactName }}
          groupId: com.azure
          safeName: ${{ parameters.ArtifactSafeName }}
      ServiceDirectory: communication
      PostSteps:
        - task: PublishCodeCoverageResults@1
          condition: and(eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['JavaTestVersion'], '1.11'), eq(variables['CurrentCloud'], 'Public'))
          inputs:
            codeCoverageTool: JaCoCo
            summaryFileLocation: sdk/communication/'${{ parameters.ArtifactName }}'/target/site/jacoco/jacoco.xml
            reportDirectory: sdk/communication/'${{ parameters.ArtifactName }}'/target/site/jacoco/
            failIfCoverageEmpty: true
      EnvVars:
        SKIP_LIVE_TEST: TRUE
