jobs:
  - job: UpdateDocMsCIConfig
    pool:
      vmImage: 'windows-2019'
    steps:
    - pwsh: |
        Write-Host "git clone https://github.com/Azure/azure-docs-sdk-java.git $(Build.SourcesDirectory)/repo"
        git clone https://github.com/Azure/azure-docs-sdk-java.git $(Build.SourcesDirectory)/repo
      displayName: Clone Documentation Repository
      ignoreLASTEXITCODE: false
    - task: PowerShell@2
      displayName: 'Update Docs.MS CI Targeted Packages'
      inputs:
        targetType: filePath
        filePath: eng/scripts/update-docs-ci.ps1
        arguments: >
          -DocRepoLocation $(Build.SourcesDirectory)/repo
          -Configs "{'path_to_config':'package.json'}"
        pwsh: true
      env:
        GH_TOKEN: $(azuresdk-github-pat)
    - template: /eng/common/pipelines/templates/steps/git-push-changes.yml
      parameters:
        BaseRepoBranch: 'master'
        BaseRepoOwner: 'Azure'
        CommitMsg: "Update targeting packages based on release csv."
        TargetRepoName: 'azure-docs-sdk-java'
        TargetRepoOwner: 'Azure'
        WorkingDirectory: $(Build.SourcesDirectory)/repo
        ScriptDirectory: $(Build.SourcesDirectory)/eng/common/scripts