jobs:
  - job: UpdateDocMsCIConfig
    pool:
      vmImage: windows-2019
    steps:
    - pwsh: |
        if ($IsWindows) {
          REG ADD HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem /f /v LongPathsEnabled /t REG_DWORD /d 1
          git config --system core.longpaths true
        }
        else {
          Write-Host "This script is not executing on Windows, skipping registry modification."
        }
      displayName: Enable Long Paths if Necessary
    - pwsh: |
        Write-Host "git clone https://github.com/Azure/azure-docs-sdk-java.git $(Build.SourcesDirectory)/repo"
        git clone https://github.com/Azure/azure-docs-sdk-java.git $(Build.SourcesDirectory)/repo
      displayName: Clone Documentation Repository
      ignoreLASTEXITCODE: false
    - task: PowerShell@2
      displayName: 'Update Docs.MS CI Targeted Packages'
      inputs:
        targetType: filePath
        filePath: eng/scripts/update-docs-ci.ps1
        arguments: >
          -DocRepoLocation $(Build.SourcesDirectory)/repo
          -Configs $(CIConfigs)
        pwsh: true
      env:
        GH_TOKEN: $(azuresdk-github-pat)
    - template: /eng/common/pipelines/templates/steps/git-push-changes.yml
      parameters:
        BaseRepoBranch: 'a-test-branch'
        BaseRepoOwner: 'Azure'
        CommitMsg: "Update targeting packages based on release csv."
        TargetRepoName: 'a-test-branch'
        TargetRepoOwner: 'Azure'
        WorkingDirectory: $(Build.SourcesDirectory)/repo
        ScriptDirectory: $(Build.SourcesDirectory)/eng/common/scripts